language: c
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl1.2-dev
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - libjpeg-dev
      - libtiff5-dev
      - libx11-6
      - libx11-dev
      - xfonts-base
      - xfonts-100dpi
      - xfonts-75dpi
services:
  - xvfb
before_install:
  - wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
  - tar -xvjpf CUnit-2.1-2-src.tar.bz2
  - cd CUnit-2.1-2
  - ./configure --prefix=$TRAVIS_BUILD_DIR
  - make
  - make install
  - export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
  - cd ..
  - sudo apt-get update -qq
  - sudo apt-get install libsmpeg-dev xfonts-cyrillic

script:
  - CFLAGS="-coverage -O0 -Wall -fprofile-arcs -ftest-coverage" make test
  - gcov src/cpu.c
  - gcov src/screen.c
  - gcov src/keyboard.c
  - gcov src/memory.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
